### ISSUE TITLE
No x64 package included in nuget package

### ISSUE THREAD

**Issue by scegg** [Quickshot/DupImageLib#1]
Referencing package dupimagelib from nuget will only download the 32-bit files.
But when running the app (in 64-bit mode), it says
Unable to load DLL 'Magick.NET-Q8-x64.Native.dll': The specified module could not be found.

**Comment by Quickshot** [comment]
I've updated the Magick.NET dependency to the newest Magick.NET-Q8-AnyCPU version in release 1.1.1 that should fix this. Please report if this solves this issue.
