### ISSUE TITLE
Index was outside the bounds of the array in DupImageLib.ImageMagickTransformer.TransformImage

### ISSUE THREAD

**Issue by scegg** [Quickshot/DupImageLib#2]
When I try to hash a jpg file using CalculateDifferenceHash256(stream), exception occurred:

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at DupImageLib.ImageMagickTransformer.TransformImage(Stream stream, Int32 width, Int32 height) in
\DupImageLib\ImageMagickTransformer.cs:line 33
   at DupImageLib.ImageHashes.CalculateDifferenceHash256(Stream sourceStream) in
\DupImageLib\ImageHashes.cs:line 243

**Comment by scegg** [comment]
In the line thrown exception, the length of pixels and imgPixels are same, 272.

**Comment by scegg** [comment]
I tried Magick.NET-Q8/Q16-AnyCPU, problem is same.

**Comment by martingagne** [comment]
I am having the same issue, can someone please help?

**Comment by Quickshot** [comment]
This should be fixed in commit fa368eb24de64ce6cb62a121904964eb1f7560fc. 
Issue was that magick.net changed how they return pixel information for grayscale images in newer versions of the library.
