### ISSUE TITLE
memory leak? → ”image.GetPixels()”

### ISSUE THREAD

**Issue by toruv326** [Quickshot/DupImageLib#3]
I think that a memory leak has occurred in the following files.
"ImageMagickTransformer.cs"
return image.GetPixels().GetValues();

I tried to rewrite it as follows.

image.Format = MagickFormat.Gray;
return image.ToByteArray();

I think that memory leak has stopped.

####
I am a beginner.
I'm sorry if I made a mistake.
English is machine translation.

**Comment by vitidev** [comment]
However you are right
I also have a memory leak and your solution helped.
