### ISSUE TITLE
Magick.NET v7.19.0.1 method not found exception

### ISSUE THREAD

**Issue by RaringCoder** [Quickshot/DupImageLib#5]
Hi,

I am attempting to call `CalculateDifferenceHash64` against the aforementioned Magick.NET version and I get exceptions as it struggles to find `QuantizeSettings.set_ColorSpace`. The property still has a setter, but evidently something else has changed in Magick.NET to make the binding at runtime fail - I notice in the later version there is a Core DLL and perhaps the `ColorSpaces` enum has also changed.

Note, the workaround for me is to roll Magick.NET back to 7.14.5, which now works. I have attempted to advance the version forwards, but immediately 7.15.0 also has issues (though the exception changes).

This is against a jpeg image.

**Comment by Quickshot** [comment]
Commit 2aea402af16f6584112dfb9392c893014e6a5734 fixes this issue by moving to using ImageSharp library instead of Magick.Net for image manipulation operations.
